[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jkeydb"
version = "0.3.0"
authors = [
  { name="The DT", email="duongtuan30306@gmail.com" }
]
description = "a simple key-value database"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/duongtuan303030/jkeydb"
"Bug Tracker" = "https://github.com/duongtuan303030/jkeydb/issues"