[tool.poetry]
name = "nsj-flask-auth"
version = "0.1.2"
description = "Modulo básico para autenticação de aplicações Flask no contexto da Nasajon"
authors = ["Lucas Assis <lucasassis@nasajon.com.br>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.1.2"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pylint = "^2.14.4"
autopep8 = "^1.6.0"
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
