[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "tumbleweed"
version = "1.0.4"
authors = [
  { name="Emil Kovacev", email="emilkovacev@gmail.com" },
]
description = "A lightweight, easy-to-setup blog framework built on Flask"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

dependencies = [
    "flask"
]

[project.urls]
"Homepage" = "https://github.com/emilkovacev/tumbleweed"
