[tool.poetry]
name = "anitui"
version = "0.1.0"
description = "A TUI to browse Anime"
authors = ["cakoshakib <cakoshakib@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.5.1"
textual = "^0.1.18"
requests = "^2.28.1"
commonmark = "^0.9.1"
pygments-arm = "^0.7.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
anitui = 'anitui.__init__:main'
