[tool.poetry]
name = "funpinpin_cli"
version = "1.1.6"
description = "funpinpin cli tool"
authors = ["funpinpin <support@funpinpin.cn>"]
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.1.2"
pickleDB = "^0.9.2"
requests = "^2.27.1"
python-graphql-client = "^0.4.3"
haikunator = "^2.1.0"
asyncio = "^3.4.3"
psutil = "^5.9.1"
questionary = "^1.10.0"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
funpinpin = "funpinpin_cli.scripts.command:cli"
