# pyproject.toml

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonrt.api"

[tool.poetry]
name = "resolv3r"
version = "1.0.1"
description = "A simple python package aimed at simplifying the vendor resolution process for network devices"
authors = ["hullabrian"]
readme="README.md"
homepage="https://github.com/HullaBrian/resolv3r"

[tool.poetry.dependencies]
python = "^3.8"
asyncssh = "^2.11.0"
netmiko = "^4.1.1"
