[tool.poetry]
name = "cqase-client"
version = "0.1.0"
description = "Custom qase client"
authors = ["alexanderlozovoy <berpress@gmail.com>"]
readme = "README.md"
repository = "https://github.com/berpress/custom-qase-client"
packages = [
    { include = "src/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.28.1"
pip = "^22.1.2"
install = "^1.3.5"

[tool.poetry.dev-dependencies]
pre-commit = "^2.19.0"
pytest = "^7.1.2"
Faker = "^13.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
