[tool.poetry]
name = "cp-common"
version = "0.1.9.1"
description = ""
authors = ["zmf963 <zmf96@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.0.1"
loguru = "^0.6.0"
rich = "^12.4.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
