[tool.poetry]
name = "jotdx"
version = "0.1.16"
description = "Get data"
authors = ["FangyangJz <fangyang.jing@hotmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
pandas = "^1.3.4"
numpy = "^1.21"
tqdm = "^4.62.3"
loguru = "^0.5.3"
httpx = "^0.20.0"
tenacity = "^8.0.1"
py-mini-racer = "^0.6.0"
click = "^8.0.3"
prettytable = "^2.2.1"
joconst = "^0.1.14"
simplejson = "^3.17.6"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
