[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PrettyGit"
version = "22.0.0"
authors = [
  { name="gmanka", email="gmankab@gmail.com" },
]
description = "very simple and user friendly interface for git"
readme = "readme.md"
# license = "GNU GENERAL PUBLIC LICENSE Version 3 https://gnu.org/licenses/gpl-3.0.en.html"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/gmankab/PrettyGit"
"Bug Tracker" = "https://github.com/gmankab/PrettyGit/issues"
