[tool.poetry]
name = "tess-flarefinder"
version = "0.5.0"
description = "Find flares in TESS"
authors = ["Keyu Xing <kyxing@mail.bnu.edu.cn>"]
license = "MIT"
homepage = "https://github.com/keyuxing/tess_flarefinder"
repository = "https://github.com/keyuxing/tess_flarefinder"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
lightkurve = "^2.3"
numba = "^0.55.2"
retrying = "^1.3"
tsfresh = "^0.19"
wotan = "^1.10"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
