[project]
name = "did-resolver"
version = "0.0.2"
description = ""
authors = [
    { name = "tintinthong", email = "justin.thong@cardstack.com" },
]
dependencies = [
    "typing-extensions>=4.3.0",
]
requires-python = ">=3.9"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.2",
    "mypy>=0.961",
    "black>=22.6.0",
]

[tool.pdm.scripts]
example = "python -m examples.run"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
