[build-system]
#requires = ["setuptools>=61.0", "matplotlib==3.5.2", "scipy==1.8.1", "pandas==1.4.3", "PyQt5==5.15.7"]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cacabplot"
version = "0.0.8"
authors = [
  { name="Casper Chris Adriaan Bekkers", email="casperbekkers2@hotmail.com" },
]
description = "A plottings tool package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.9"
#classifiers = [
#    "Programming Language :: Python :: 3",
#    "License :: OSI Approved :: MIT License",
#    "Operating System :: OS Independent",
#]